version: '3'
services:

  app:
    container_name: forwarder_bot_app
    image: awnulled/forwarder-bot/app
    restart: on-failure
    command: bash -c "gunicorn src.main:create_bot_app
                      -k aiohttp.GunicornWebWorker
                      -b 0.0.0.0:80
                      --keep-alive 200
                      --timeout 200
                      --graceful-timeout 200"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    env_file:
      - .env.dev
  db:
    container_name: forwarder_bot_db
    image: awnulled/forwarder-bot/postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  pgbouncer:
    container_name: forwarder_bot_pgbouncer
    image: awnulled/forwarder-bot/pgbouncer
    restart: on-failure
    ports:
      - "0.0.0.0:6432:6432"
    depends_on:
      - db

  redis:
    container_name: forwarder_bot_redis
    image: redis:6-buster
    restart: on-failure
    command: --appendonly yes
    volumes:
      - redisdata:/data
    ports:
      - "0.0.0.0:6379:6379"

volumes:
  pgdata:
  redisdata:

networks:
  default: