"""Add new field into Target model

Revision ID: 49da7f41797d
Revises: 7854e0f86887
Create Date: 2021-03-02 02:42:50.900894

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49da7f41797d"
down_revision = "7854e0f86887"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "forwarder_targets", ["id"])
    op.create_unique_constraint(None, "subscribers", ["id"])
    op.add_column("targets", sa.Column("fetch_count", sa.SmallInteger(), nullable=False))
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("targets", "fetch_count")
    op.drop_constraint(None, "subscribers", type_="unique")
    op.drop_constraint(None, "forwarder_targets", type_="unique")
    # ### end Alembic commands ###
